pipeline:
  name: ecr-task
  identifier: ecrtask
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ecr-stage
        identifier: ecrstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: IDE
                    configuration:
                      stackName: ecr-creation
                      connectorRef: AWS1
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecr.yaml
                              connectorRef: Conector2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                  timeout: 10m
        tags: {}
    - stage:
        name: ecs-cluster-deploy
        identifier: ecsclusterdeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: ECS
          service:
            serviceRef: ecsservice
          environment:
            environmentRef: ecsenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: ecsinf
          execution:
            steps:
              - step:
                  name: ECS Rolling Deploy
                  identifier: ecsRollingDeploy
                  type: EcsRollingDeploy
                  timeout: 10m
                  spec: {}
            rollbackSteps:
              - step:
                  name: ECS Rolling Rollback
                  identifier: ecsRollingRollback
                  type: EcsRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
