pipeline:
  name: ecr-task
  identifier: ecrtask
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ecr-stage
        identifier: ecrstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: IDE
                    configuration:
                      stackName: ecr-creation
                      connectorRef: AWS1
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecr.yaml
                              connectorRef: Conector2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                      parameterOverrides:
                        - name: RepoName
                          value: ecr-repo
                          type: String
                  timeout: 10m
        tags: {}
  variables:
    - name: RepoName
      type: String
      description: ""
      required: false
      value: <+input>
