AWSTemplateFormatVersion: "2010-09-09"
Description: "Ecr repository"
Resources:
  MyRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "tes-repository"
  
https://developer.harness.io/docs/continuous-integration/get-started/overview
